"""add intent to edge_text_log

Revision ID: 048c424b3b79
Revises: 
Create Date: 2025-11-29 12:34:42.210353
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "048c424b3b79"
down_revision = None
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_text_logs', sa.Column('intent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge_text_logs', 'intent')
    # ### end Alembic commands ###
